<?php

// autoload.php @generated by Composer
require '/path/to/sdk/vendor/autoload.php';
use Qiniu\Auth;
use Qiniu\Storage\BucketManager;

$accessKey = 'U3Is3mssiNMUt6d3np4p55s7ltQ1ESh-NZBii7tI';
$secretKey = '45SX6CQvMIH6P_WzOAHUwgiy1S4TDDk04E66bzGt';
$auth = new Auth($accessKey, $secretKey);


$bucketMgr = new BucketManager($auth);
$bucket = 'phpsdk';
$key = 'php-logo.png';
$key3 = 'php-logo3.png';

$err = $bucketMgr->move($bucket, $key, $bucket, $key3);
echo "\n====> move result: \n";
if ($err !== null) {
    var_dump($err);
} else {
    echo "Success!";
}